using System;
using System.Collections;
using System.Linq;
using System.Text;

namespace ClarionDctAddin
{
    // Emit one class / interface per table with properties typed from
    // Clarion's DataType strings. Used by both the C# and TypeScript
    // model-class export tools.
    internal static class ModelClassesGenerator
    {
        public sealed class Options
        {
            public string Namespace = "ClarionModels";
            public bool IncludeDescriptions = true;
        }

        public static string GenerateCSharp(object dict, Options opt)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by Clarion Dictionary Tasker  " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
            sb.AppendLine("// Source dictionary: " + DictModel.GetDictionaryName(dict));
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace " + (string.IsNullOrEmpty(opt.Namespace) ? "ClarionModels" : opt.Namespace));
            sb.AppendLine("{");
            foreach (var t in DictModel.GetTables(dict)
                .OrderBy(x => DictModel.AsString(DictModel.GetProp(x, "Name")), StringComparer.OrdinalIgnoreCase))
            {
                var tName = DictModel.AsString(DictModel.GetProp(t, "Name")) ?? "Model";
                var tDesc = DictModel.AsString(DictModel.GetProp(t, "Description")) ?? "";
                if (opt.IncludeDescriptions && !string.IsNullOrEmpty(tDesc))
                {
                    sb.AppendLine("    /// <summary>");
                    foreach (var line in tDesc.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                        sb.AppendLine("    /// " + XmlEscape(line));
                    sb.AppendLine("    /// </summary>");
                }
                sb.AppendLine("    public class " + ClassName(tName));
                sb.AppendLine("    {");
                var fields = DictModel.GetProp(t, "Fields") as IEnumerable;
                if (fields != null) foreach (var f in fields)
                {
                    if (f == null) continue;
                    var label = DictModel.AsString(DictModel.GetProp(f, "Label")) ?? "";
                    if (string.IsNullOrEmpty(label)) continue;
                    var dt   = DictModel.AsString(DictModel.GetProp(f, "DataType")) ?? "";
                    var desc = DictModel.AsString(DictModel.GetProp(f, "Description")) ?? "";
                    var cs   = MapToCSharp(dt);
                    if (opt.IncludeDescriptions && !string.IsNullOrEmpty(desc))
                        sb.AppendLine("        /// <summary>" + XmlEscape(desc.Replace("\r", " ").Replace("\n", " ")) + "</summary>");
                    sb.AppendLine("        public " + cs + " " + PascalName(label) + " { get; set; }");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string GenerateTypeScript(object dict, Options opt)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by Clarion Dictionary Tasker  " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
            sb.AppendLine("// Source dictionary: " + DictModel.GetDictionaryName(dict));
            sb.AppendLine();
            foreach (var t in DictModel.GetTables(dict)
                .OrderBy(x => DictModel.AsString(DictModel.GetProp(x, "Name")), StringComparer.OrdinalIgnoreCase))
            {
                var tName = DictModel.AsString(DictModel.GetProp(t, "Name")) ?? "Model";
                var tDesc = DictModel.AsString(DictModel.GetProp(t, "Description")) ?? "";
                if (opt.IncludeDescriptions && !string.IsNullOrEmpty(tDesc))
                {
                    sb.AppendLine("/**");
                    foreach (var line in tDesc.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                        sb.AppendLine(" * " + line);
                    sb.AppendLine(" */");
                }
                sb.AppendLine("export interface " + ClassName(tName) + " {");
                var fields = DictModel.GetProp(t, "Fields") as IEnumerable;
                if (fields != null) foreach (var f in fields)
                {
                    if (f == null) continue;
                    var label = DictModel.AsString(DictModel.GetProp(f, "Label")) ?? "";
                    if (string.IsNullOrEmpty(label)) continue;
                    var dt   = DictModel.AsString(DictModel.GetProp(f, "DataType")) ?? "";
                    var desc = DictModel.AsString(DictModel.GetProp(f, "Description")) ?? "";
                    var ts   = MapToTypeScript(dt);
                    if (opt.IncludeDescriptions && !string.IsNullOrEmpty(desc))
                        sb.AppendLine("    /** " + desc.Replace("\r", " ").Replace("\n", " ").Replace("*/", "*\\/") + " */");
                    sb.AppendLine("    " + CamelName(label) + ": " + ts + ";");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
            return sb.ToString();
        }

        static string MapToCSharp(string clarionType)
        {
            switch ((clarionType ?? "").ToUpperInvariant())
            {
                case "STRING": case "CSTRING": case "PSTRING": case "MEMO": return "string";
                case "BYTE":                                        return "byte";
                case "SHORT": case "USHORT":                        return "short";
                case "LONG":  case "ULONG":                         return "int";
                case "DATE":                                        return "DateTime";
                case "TIME":                                        return "TimeSpan";
                case "REAL":  case "SREAL":                         return "double";
                case "DECIMAL": case "PDECIMAL":                    return "decimal";
                case "GROUP": case "QUEUE":                         return "object";
                default: return "string";
            }
        }

        static string MapToTypeScript(string clarionType)
        {
            switch ((clarionType ?? "").ToUpperInvariant())
            {
                case "STRING": case "CSTRING": case "PSTRING": case "MEMO": return "string";
                case "BYTE": case "SHORT": case "USHORT":
                case "LONG": case "ULONG":
                case "REAL": case "SREAL":
                case "DECIMAL": case "PDECIMAL":
                    return "number";
                case "DATE": case "TIME":       return "string";
                default: return "string";
            }
        }

        static string ClassName(string name)
        {
            if (string.IsNullOrEmpty(name)) return "Model";
            var parts = name.Split(new[] { '_', '-', ' ', '.' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var p in parts)
            {
                if (p.Length == 0) continue;
                sb.Append(char.ToUpperInvariant(p[0]));
                if (p.Length > 1) sb.Append(p.Substring(1).ToLowerInvariant());
            }
            var s = sb.ToString();
            if (s.Length == 0) return "Model";
            if (!char.IsLetter(s[0]) && s[0] != '_') s = "_" + s;
            return s;
        }

        static string PascalName(string label) { return ClassName(label); }

        static string CamelName(string label)
        {
            var p = ClassName(label);
            if (string.IsNullOrEmpty(p)) return "field";
            return char.ToLowerInvariant(p[0]) + p.Substring(1);
        }

        static string XmlEscape(string s)
        {
            return (s ?? "")
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }
    }
}
